### ISSUE TITLE
Refuel Order

### ISSUE THREAD

**Issue by Sophisanimus** [OuterDeepSpace/OuterDeepSpace#27] opened 2016-03-28 02:07 UTC
The Refuel At order seems broken - ordering ships to Refuel At a location with refueling capacity seems to only execute a Move To command, and any additional orders in the queue will be executed immediately without any refueling.  This renders Refuel At no different than Move To as far as I can tell.

**Comment by Ragora** [comment] 2016-03-28 15:35
I do seem to be having trouble getting some of my vessels to refuel personally. I haven't given them any orders aside from refueling and they simply don't want to do it.

**Comment by ghost** [comment] 2016-03-31 01:40
I haven't noticed any issues with refueling yet. When given a refuel order, my fleets seem to move, take on as much fuel as the planet can provide them with, then continue with the next order on the list. 

It is true I haven't been keeping this under a microscope, but is it possible the hazy fuel cap mechanics are making it look like there's a bug where there isn't one? I believe a fleet with more fuel than the planet can provide (very low numbers in some cases) will arrive and then immediately execute the next order, since there's no point in staying.

**Comment by Malxe** [comment] 2016-03-31 06:14
Tested and confirmed Refuel At functions correctly by having a fleet wait at a system with refueling up to the maximum possible for the system before moving to the next command in the list. Closing issue #27.

**Closed as completed by Malxe** 2016-03-31 06:14 UTC
Labels: Invalid, Question, High Priority
